version: "2.2"

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - treemory-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  app:
    restart: "always"
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
    entrypoint: ["/bin/bash"]
    command:
      - -c
      - |
        pnpm install
        pnpm prisma migrate dev
        pnpm dev
    ports:
      - 3000:3000
    networks:
      - treemory-network
volumes:
  mysql:
    driver: local
networks:
  treemory-network:
    driver: bridge
